// Indicates how a piece of data was derived.
// 🟢 Verified   — official source (label, artist)
// 🔵 Calculated — computed by BSM from real data
// 🟣 Community  — user-driven contributions
// 🟠 AI         — GPT-4o generated
// ⚪ Estimated  — inferred, not confirmed
//
// Tapping the badge opens a small explanation — title tooltips don't exist on
// touch screens, and this page is mobile-first.

import { useEffect, useRef, useState } from 'react';

export type ConfidenceLevel = 'verified' | 'calculated' | 'community' | 'ai' | 'estimated';

const CONF: Record<ConfidenceLevel, { dot: string; label: string; meaning: string }> = {
  verified: {
    dot: 'bg-emerald-500',
    label: 'Verified',
    meaning: 'This comes from an official or primary source — the label, the artist, or their published records.',
  },
  calculated: {
    dot: 'bg-sky-500',
    label: 'Calculated',
    meaning: 'Computed from real concert records on Setlist.fm. The numbers are only as complete as the archive itself.',
  },
  community: {
    dot: 'bg-violet-500',
    label: 'Community',
    meaning: 'Contributed by players and fans. Reviewed, but not independently confirmed.',
  },
  ai: {
    dot: 'bg-amber-500',
    label: 'AI',
    meaning: 'Generated by AI analysis. Useful as a starting point — treat details with healthy skepticism.',
  },
  estimated: {
    dot: 'bg-gray-500',
    label: 'Estimated',
    meaning: 'Inferred from catalog data until better information arrives. Not confirmed by a primary source.',
  },
};

interface Props {
  level: ConfidenceLevel;
  className?: string;
}

export default function KnowledgeConfidenceBadge({ level, className = '' }: Props) {
  const c = CONF[level];
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLSpanElement>(null);

  useEffect(() => {
    if (!open) return;
    function onOutside(e: MouseEvent | TouchEvent) {
      if (wrapRef.current && !wrapRef.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener('mousedown', onOutside);
    document.addEventListener('touchstart', onOutside);
    return () => {
      document.removeEventListener('mousedown', onOutside);
      document.removeEventListener('touchstart', onOutside);
    };
  }, [open]);

  return (
    <span ref={wrapRef} className={`relative inline-flex ${className}`}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        aria-label={`${c.label} — tap for what this means`}
        className="inline-flex items-center gap-1 text-[10px] font-medium uppercase tracking-widest text-gray-400 hover:text-gray-200 focus:outline-none focus-visible:ring-1 focus-visible:ring-gray-500 rounded transition-colors cursor-help"
      >
        <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${c.dot}`} />
        {c.label}
      </button>

      {open && (
        <span
          role="tooltip"
          className="absolute z-30 top-full left-1/2 -translate-x-1/2 mt-2 w-56 rounded-lg border border-gray-700 bg-gray-900 px-3 py-2.5 shadow-xl shadow-black/50 normal-case tracking-normal"
        >
          <span className="flex items-center gap-1.5 mb-1">
            <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${c.dot}`} />
            <span className="text-[10px] font-bold uppercase tracking-widest text-gray-300">{c.label}</span>
          </span>
          <span className="block text-[11px] leading-relaxed text-gray-400">{c.meaning}</span>
        </span>
      )}
    </span>
  );
}
