// Indicates how a piece of data was derived.
// 🟢 Verified   — official source (label, artist)
// 🔵 Calculated — computed by BSM from real data
// 🟣 Community  — user-driven contributions
// 🟠 AI         — GPT-4o generated
// ⚪ Estimated  — inferred, not confirmed

export type ConfidenceLevel = 'verified' | 'calculated' | 'community' | 'ai' | 'estimated';

const CONF: Record<ConfidenceLevel, { dot: string; label: string; title: string }> = {
  verified:   { dot: 'bg-emerald-500', label: 'Verified',   title: 'From an official or primary source' },
  calculated: { dot: 'bg-sky-500',     label: 'Calculated', title: 'Computed by BSM from real performance data' },
  community:  { dot: 'bg-violet-500',  label: 'Community',  title: 'Contributed by users' },
  ai:         { dot: 'bg-amber-500',   label: 'AI',         title: 'Generated by GPT-4o — may need verification' },
  estimated:  { dot: 'bg-gray-500',    label: 'Estimated',  title: 'Inferred; not confirmed by a primary source' },
};

interface Props {
  level: ConfidenceLevel;
  className?: string;
}

export default function KnowledgeConfidenceBadge({ level, className = '' }: Props) {
  const c = CONF[level];
  return (
    <span
      title={c.title}
      className={`inline-flex items-center gap-1 text-[10px] font-medium uppercase tracking-widest text-gray-400 ${className}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${c.dot}`} />
      {c.label}
    </span>
  );
}
