// Song Health — Phase Z.17.5.
//
// One registry describing every song-analysis module BSM knows about: what
// it needs, how to check whether a given song has it, and (where one exists)
// the single action that fills it. This is the server-side source of truth
// that both the Song Card's health breakdown AND the album/band rollups AND
// the "Analyze Song" pipeline read from — no module status is ever computed
// twice in two different places.
//
// Deliberately excluded (see Phase Z.17.5 report for reasoning, not repeated
// here): SongAiSpectrum (a secondary AI opinion — re-litigating it would
// undo Z.17's "one clean spectrum" decision), SongContextAnalysis /
// AudienceProfile (derivative/composite, not primary source data), Node
// Graph (a cross-song visualization, not a per-song artifact).

import { prisma } from '../lib/prisma.js';
import { aiAnalysisService } from './aiAnalysisService.js';
import { songMusicScoreService } from './songMusicScoreService.js';
import { themeAnalysisService } from './themeAnalysisService.js';
import { genreSpectrumService } from './genreSpectrumService.js';
import { songResearchService } from './songResearchService.js';
import { aiLyricService } from './aiLyricService.js';
import type {
  ModuleDataStatus,
  SongHealth,
  AggregateHealth,
} from '@band-spectrum-mapper/shared';

// ---------------------------------------------------------------------------
// Module registry
// ---------------------------------------------------------------------------

export type ModuleKey =
  | 'metadata' | 'lyrics' | 'liveData' | 'spectrum' | 'rhythm'
  | 'theme' | 'genre' | 'summary' | 'community' | 'trivia' | 'media';

interface ModuleDef {
  key: ModuleKey;
  title: string;
  /** Contribution to the health score. 0 = tracked but excluded (shown, not scored). */
  weight: number;
  /** Position in the auto "Analyze Song" pipeline; null = not part of it. */
  pipelineOrder: number | null;
}

const MODULE_DEFS: ModuleDef[] = [
  { key: 'metadata',  title: 'Metadata',    weight: 0.5, pipelineOrder: null },
  { key: 'lyrics',    title: 'Lyrics',      weight: 1,   pipelineOrder: 1 },
  { key: 'liveData',  title: 'Live Data',   weight: 1,   pipelineOrder: null },
  { key: 'spectrum',  title: 'Spectrum',    weight: 1,   pipelineOrder: 2 },
  { key: 'rhythm',    title: 'Rhythm',      weight: 1,   pipelineOrder: 3 },
  { key: 'theme',     title: 'Theme',       weight: 1,   pipelineOrder: 4 },
  { key: 'genre',     title: 'Genre',       weight: 1,   pipelineOrder: 5 },
  { key: 'summary',   title: 'AI Summary',  weight: 1,   pipelineOrder: 6 },
  { key: 'community', title: 'Community',  weight: 0.5, pipelineOrder: null },
  // Trivia and Media are tracked and shown, but excluded from the score:
  // Trivia has no persisted per-song artifact to be "missing" (see below),
  // and Media has no backing system at all yet — a module that can never
  // possibly gain data shouldn't permanently cap every song below 100%.
  { key: 'trivia',    title: 'Trivia',      weight: 0,   pipelineOrder: null },
  { key: 'media',     title: 'Media',       weight: 0,   pipelineOrder: null },
];

/** Modules the "Analyze Song" pipeline can actually generate, in run order. */
export const PIPELINE_MODULES: ModuleKey[] = MODULE_DEFS
  .filter((m) => m.pipelineOrder !== null)
  .sort((a, b) => (a.pipelineOrder ?? 0) - (b.pipelineOrder ?? 0))
  .map((m) => m.key);

// ---------------------------------------------------------------------------
// Per-song input — callers pass in whatever they already loaded (the wiki
// song endpoint already has score/lyrics/bandRpgProfile/musicScore) so this
// service only fetches the pieces nothing else needed yet.
// ---------------------------------------------------------------------------

export interface SongHealthInput {
  songId: string;
  albumId: string | null;
  trackNumber: number | null;
  durationSeconds: number | null;
  hasLyrics: boolean;
  isInstrumental: boolean;
  hasScore: boolean;
  scoreSource: string | null;
  scoreUpdatedAt: string | null;
  hasMusicScore: boolean;
  musicScoreUpdatedAt: string | null;
  hasLiveProfile: boolean;
}

/** Human-readable provenance for the Spectrum module's confidence badge. */
function describeSpectrumSource(source: string | null): { confidence: ModuleDataStatus['confidence']; label: string } {
  switch (source) {
    case 'manual': return { confidence: 'verified', label: 'Hand-entered by a curator.' };
    case 'audio':  return { confidence: 'calculated', label: 'Derived from audio signal analysis.' };
    case 'import': return { confidence: 'estimated', label: 'Loaded from an imported dataset.' };
    case 'ai':     return { confidence: 'ai', label: 'Generated by AI analysis of the lyrics and context.' };
    default:       return { confidence: 'ai', label: 'Source predates provenance tracking — likely AI-generated.' };
  }
}

async function fetchExtras(songId: string) {
  const [themeCount, genre, research, commentCount] = await Promise.all([
    prisma.songThemeScore.count({ where: { songId } }),
    prisma.songAiGenreSpectrum.findUnique({ where: { songId }, select: { updatedAt: true } }),
    prisma.songResearch.findUnique({ where: { songId }, select: { updatedAt: true } }),
    prisma.songComment.count({ where: { songId } }),
  ]);
  return { themeCount, genre, research, commentCount };
}

export async function computeSongHealth(input: SongHealthInput): Promise<SongHealth> {
  const { themeCount, genre, research, commentCount } = await fetchExtras(input.songId);

  const metadataComplete = input.albumId !== null && input.trackNumber !== null && input.durationSeconds !== null;
  const metadataPartial = input.albumId !== null || input.trackNumber !== null || input.durationSeconds !== null;

  const modules: ModuleDataStatus[] = [
    {
      moduleKey: 'metadata', title: 'Metadata',
      status: metadataComplete ? 'ready' : metadataPartial ? 'partial' : 'missing',
      source: 'manual', confidence: 'verified', lastUpdated: null,
      hasData: metadataComplete, canGenerate: false, canFetch: false, canRepair: false,
      progress: null, notes: null,
      adminAction: metadataComplete ? null : {
        kind: 'route', label: 'Edit in Library', to: `/library/songs/${input.songId}`,
      },
    },
    {
      moduleKey: 'lyrics', title: 'Lyrics',
      status: (input.hasLyrics || input.isInstrumental) ? 'ready' : 'missing',
      source: input.hasLyrics ? 'manual' : null, confidence: input.hasLyrics ? 'verified' : null, lastUpdated: null,
      hasData: input.hasLyrics || input.isInstrumental, canGenerate: !input.hasLyrics, canFetch: false, canRepair: false,
      progress: null, notes: input.isInstrumental ? 'Instrumental — no lyrics expected.' : null,
      adminAction: (input.hasLyrics || input.isInstrumental) ? null : {
        kind: 'endpoint', label: 'Fetch Lyrics (AI recall)', method: 'POST', path: `/api/songs/${input.songId}/ai-lyrics`,
      },
    },
    {
      moduleKey: 'liveData', title: 'Live Data',
      status: input.hasLiveProfile ? 'ready' : 'missing',
      source: input.hasLiveProfile ? 'calculated' : null, confidence: input.hasLiveProfile ? 'calculated' : null, lastUpdated: null,
      hasData: input.hasLiveProfile, canGenerate: false, canFetch: !input.hasLiveProfile, canRepair: false,
      progress: null, notes: null,
      adminAction: input.hasLiveProfile ? null : {
        kind: 'route', label: 'Fetch Live Data', to: '/admin/band-rpg',
      },
    },
    {
      moduleKey: 'spectrum', title: 'Spectrum',
      status: input.hasScore ? 'ready' : 'missing',
      source: input.scoreSource,
      confidence: input.hasScore ? describeSpectrumSource(input.scoreSource).confidence : null,
      lastUpdated: input.scoreUpdatedAt,
      hasData: input.hasScore, canGenerate: !input.hasScore, canFetch: false, canRepair: input.hasScore,
      progress: null,
      notes: input.hasScore ? describeSpectrumSource(input.scoreSource).label : null,
      adminAction: {
        kind: 'endpoint',
        label: input.hasScore ? 'Repair Spectrum' : 'Generate Song Spectrum',
        method: 'POST', path: `/api/analysis/ai/${input.songId}/core-score/generate`,
      },
    },
    {
      moduleKey: 'rhythm', title: 'Rhythm',
      status: input.hasMusicScore ? 'ready' : 'missing',
      source: input.hasMusicScore ? 'ai' : null, confidence: input.hasMusicScore ? 'ai' : null, lastUpdated: input.musicScoreUpdatedAt,
      hasData: input.hasMusicScore, canGenerate: !input.hasMusicScore, canFetch: false, canRepair: input.hasMusicScore,
      progress: null, notes: null,
      adminAction: {
        kind: 'endpoint',
        label: input.hasMusicScore ? 'Re-analyze Rhythm' : 'Analyze Rhythm',
        method: 'POST', path: `/api/analysis/ai/${input.songId}/music-score/regenerate`,
      },
    },
    {
      moduleKey: 'theme', title: 'Theme',
      status: themeCount > 0 ? 'ready' : 'missing',
      source: themeCount > 0 ? 'ai' : null, confidence: themeCount > 0 ? 'ai' : null, lastUpdated: null,
      hasData: themeCount > 0, canGenerate: themeCount === 0, canFetch: false, canRepair: themeCount > 0,
      progress: null, notes: null,
      adminAction: {
        kind: 'endpoint',
        label: themeCount > 0 ? 'Repair Themes' : 'Generate Themes',
        method: 'POST', path: `/api/analysis/ai/${input.songId}/themes/regenerate`,
      },
    },
    {
      moduleKey: 'genre', title: 'Genre',
      status: genre ? 'ready' : 'missing',
      source: genre ? 'ai' : null, confidence: genre ? 'ai' : null, lastUpdated: genre?.updatedAt.toISOString() ?? null,
      hasData: !!genre, canGenerate: !genre, canFetch: false, canRepair: !!genre,
      progress: null, notes: null,
      adminAction: {
        kind: 'endpoint',
        label: genre ? 'Repair Genre Appeal' : 'Generate Genre Appeal',
        method: 'POST', path: `/api/analysis/ai/${input.songId}/genre-spectrum/regenerate`,
      },
    },
    {
      moduleKey: 'summary', title: 'AI Summary',
      status: research ? 'ready' : 'missing',
      source: research ? 'ai' : null, confidence: research ? 'ai' : null, lastUpdated: research?.updatedAt.toISOString() ?? null,
      hasData: !!research, canGenerate: !research, canFetch: false, canRepair: !!research,
      progress: null, notes: null,
      adminAction: {
        kind: 'endpoint',
        label: research ? 'Repair AI Summary' : 'Generate AI Summary',
        method: 'POST', path: `/api/analysis/ai/${input.songId}/research/regenerate`,
      },
    },
    {
      moduleKey: 'community', title: 'Community',
      status: commentCount > 0 ? 'ready' : 'missing',
      source: commentCount > 0 ? 'community' : null, confidence: commentCount > 0 ? 'community' : null, lastUpdated: null,
      hasData: commentCount > 0, canGenerate: false, canFetch: false, canRepair: false,
      progress: null, notes: 'User-authored — no admin action to generate discussion.',
      adminAction: null,
    },
    {
      moduleKey: 'trivia', title: 'Trivia',
      status: 'skipped',
      source: 'calculated', confidence: 'calculated', lastUpdated: null,
      hasData: true, canGenerate: false, canFetch: false, canRepair: false,
      progress: null, notes: 'Generated live from existing scores and lyrics — no persisted per-song artifact to track.',
      adminAction: null,
    },
    {
      moduleKey: 'media', title: 'Media',
      status: 'missing',
      source: null, confidence: null, lastUpdated: null,
      hasData: false, canGenerate: false, canFetch: false, canRepair: false,
      progress: null, notes: 'No song-level media system exists yet.',
      adminAction: null,
    },
  ];

  const scoredModules = modules.filter((m) => MODULE_DEFS.find((d) => d.key === m.moduleKey)!.weight > 0);
  const totalWeight = scoredModules.reduce((sum, m) => sum + MODULE_DEFS.find((d) => d.key === m.moduleKey)!.weight, 0);
  const earnedWeight = scoredModules.reduce(
    (sum, m) => sum + (m.hasData ? MODULE_DEFS.find((d) => d.key === m.moduleKey)!.weight : 0), 0,
  );
  const overallPct = totalWeight > 0 ? Math.round((earnedWeight / totalWeight) * 100) : 100;

  return { overallPct, modules };
}

// ---------------------------------------------------------------------------
// Bulk health — for Album/Band rollups. Batched existence checks across an
// entire song-ID set (one query per module, not one per song) so a 70-song
// discography costs the same handful of queries as a single song.
// ---------------------------------------------------------------------------

export async function computeAggregateHealth(songIds: string[]): Promise<AggregateHealth> {
  if (songIds.length === 0) {
    return { overallPct: 100, songCount: 0, moduleCoverage: [] };
  }

  const [
    songs, themeRows, genreRows, researchRows, commentRows,
  ] = await Promise.all([
    prisma.song.findMany({
      where: { id: { in: songIds } },
      select: {
        id: true, albumId: true, trackNumber: true, durationSeconds: true,
        isInstrumental: true,
        lyrics: { where: { isPrimary: true }, select: { id: true }, take: 1 },
        score: { select: { id: true } },
        musicScore: { select: { id: true } },
        bandRpgProfile: { select: { id: true } },
      },
    }),
    prisma.songThemeScore.groupBy({ by: ['songId'], where: { songId: { in: songIds } }, _count: { id: true } }),
    prisma.songAiGenreSpectrum.findMany({ where: { songId: { in: songIds } }, select: { songId: true } }),
    prisma.songResearch.findMany({ where: { songId: { in: songIds } }, select: { songId: true } }),
    prisma.songComment.groupBy({ by: ['songId'], where: { songId: { in: songIds } }, _count: { id: true } }),
  ]);

  const themeSet = new Set(themeRows.map((r) => r.songId));
  const genreSet = new Set(genreRows.map((r) => r.songId));
  const researchSet = new Set(researchRows.map((r) => r.songId));
  const commentSet = new Set(commentRows.map((r) => r.songId));

  const n = songs.length;
  const coverage = (predicate: (s: (typeof songs)[number]) => boolean) =>
    songs.filter(predicate).length;

  const moduleCoverage: AggregateHealth['moduleCoverage'] = [
    { key: 'metadata' as const, title: 'Metadata', count: coverage((s) => s.albumId !== null && s.trackNumber !== null && s.durationSeconds !== null) },
    { key: 'lyrics' as const,   title: 'Lyrics',   count: coverage((s) => s.lyrics.length > 0 || s.isInstrumental) },
    { key: 'liveData' as const, title: 'Live Data',count: coverage((s) => !!s.bandRpgProfile) },
    { key: 'spectrum' as const, title: 'Spectrum', count: coverage((s) => !!s.score) },
    { key: 'rhythm' as const,   title: 'Rhythm',   count: coverage((s) => !!s.musicScore) },
    { key: 'theme' as const,    title: 'Theme',    count: coverage((s) => themeSet.has(s.id)) },
    { key: 'genre' as const,    title: 'Genre',    count: coverage((s) => genreSet.has(s.id)) },
    { key: 'summary' as const,  title: 'AI Summary', count: coverage((s) => researchSet.has(s.id)) },
    { key: 'community' as const,title: 'Community',count: coverage((s) => commentSet.has(s.id)) },
  ].map((m) => ({
    moduleKey: m.key, title: m.title, songsComplete: m.count,
    pct: n > 0 ? Math.round((m.count / n) * 100) : 100,
  }));

  const scoredKeys = new Set(MODULE_DEFS.filter((d) => d.weight > 0).map((d) => d.key));
  const scored = moduleCoverage.filter((m) => scoredKeys.has(m.moduleKey as ModuleKey));
  const totalWeight = scored.reduce((sum, m) => sum + MODULE_DEFS.find((d) => d.key === m.moduleKey)!.weight, 0);
  const earnedWeight = scored.reduce(
    (sum, m) => sum + (m.pct / 100) * MODULE_DEFS.find((d) => d.key === m.moduleKey)!.weight, 0,
  );
  const overallPct = totalWeight > 0 ? Math.round((earnedWeight / totalWeight) * 100) : 100;

  return { overallPct, songCount: n, moduleCoverage };
}

// ---------------------------------------------------------------------------
// Pipeline dispatch — the single place that knows how to generate each
// module. "Analyze Song" and the job queue both call this; per-module admin
// buttons hit the same underlying endpoints directly, so there is exactly
// one code path per module, not two.
// ---------------------------------------------------------------------------

export async function generateModule(moduleKey: ModuleKey, songId: string): Promise<void> {
  switch (moduleKey) {
    case 'lyrics':   await aiLyricService.recallAndStore(songId); return;
    case 'spectrum': await aiAnalysisService.generateCoreScore(songId); return;
    case 'rhythm':   await songMusicScoreService.getOrCreate(songId); return;
    case 'theme':    await themeAnalysisService.getOrCreate(songId); return;
    case 'genre':    await genreSpectrumService.getOrCreate(songId); return;
    case 'summary':  await songResearchService.getOrCreate(songId); return;
    default:
      throw new Error(`Module "${moduleKey}" is not part of the auto-generate pipeline`);
  }
}

/**
 * Runs every pipeline-eligible module for a song, skipping ones that already
 * have data. Returns a per-module outcome log — never throws for an
 * individual stage failure, so one bad AI call doesn't abort the rest.
 */
export async function runSongPipeline(
  songId: string,
  songTitle: string,
  isCancelled: () => Promise<boolean>,
): Promise<Array<{ songId: string; songTitle: string; moduleKey: string; outcome: 'skipped' | 'generated' | 'failed'; error?: string }>> {
  const song = await prisma.song.findUnique({
    where: { id: songId },
    select: {
      albumId: true, trackNumber: true, durationSeconds: true, isInstrumental: true,
      lyrics: { where: { isPrimary: true }, select: { id: true }, take: 1 },
      score: { select: { id: true, source: true, updatedAt: true } },
      musicScore: { select: { id: true, updatedAt: true } },
      bandRpgProfile: { select: { id: true } },
    },
  });
  if (!song) throw new Error('Song not found');

  const health = await computeSongHealth({
    songId,
    albumId: song.albumId,
    trackNumber: song.trackNumber,
    durationSeconds: song.durationSeconds,
    hasLyrics: song.lyrics.length > 0,
    isInstrumental: song.isInstrumental,
    hasScore: !!song.score,
    scoreSource: song.score?.source ?? null,
    scoreUpdatedAt: song.score?.updatedAt.toISOString() ?? null,
    hasMusicScore: !!song.musicScore,
    musicScoreUpdatedAt: song.musicScore?.updatedAt.toISOString() ?? null,
    hasLiveProfile: !!song.bandRpgProfile,
  });

  const results: Array<{ songId: string; songTitle: string; moduleKey: string; outcome: 'skipped' | 'generated' | 'failed'; error?: string }> = [];

  for (const moduleKey of PIPELINE_MODULES) {
    if (await isCancelled()) break;
    const status = health.modules.find((m) => m.moduleKey === moduleKey);
    if (status?.hasData) {
      results.push({ songId, songTitle, moduleKey, outcome: 'skipped' });
      continue;
    }
    try {
      await generateModule(moduleKey, songId);
      results.push({ songId, songTitle, moduleKey, outcome: 'generated' });
    } catch (e) {
      results.push({ songId, songTitle, moduleKey, outcome: 'failed', error: e instanceof Error ? e.message : 'Unknown error' });
    }
  }

  return results;
}
