import { Link } from 'react-router-dom';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-bold mb-3 text-surface-900">{title}</h2>
      <div className="text-sm text-surface-700 leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-surface-50">
      <div className="max-w-3xl mx-auto px-6 py-12">

        {/* Nav */}
        <nav className="flex items-center gap-3 text-sm mb-10 text-surface-600">
          <Link to="/" className="hover:text-surface-900 transition-colors">Home</Link>
          <span className="text-surface-300">·</span>
          <Link to="/view" className="hover:text-surface-900 transition-colors">Library</Link>
          <span className="text-surface-300">·</span>
          <Link to="/help" className="hover:text-surface-900 transition-colors">Help</Link>
        </nav>

        <h1 className="text-3xl font-bold tracking-tight mb-2">Legal Notice &amp; Disclaimer</h1>
        <p className="text-surface-500 text-sm mb-10">
          Please read this carefully. By using Band Spectrum Mapper, you agree to these terms.
        </p>

        <Section title="1. Nature of This Site">
          <p>
            Band Spectrum Mapper is an independent, fan-built music analysis and discussion tool.
            It is a personal project created for educational, critical, and commentary purposes.
            It is not a commercial product, not monetised, and not affiliated with any record label,
            artist management company, music publisher, or streaming service.
          </p>
          <p>
            The analysis, scores, and commentary presented on this site represent personal fan
            interpretations and AI-generated critical opinion. They do not represent the views,
            positions, or official statements of any artist, band, or rights holder.
          </p>
        </Section>

        <Section title="2. No Affiliation with Any Artist or Band">
          <p>
            Band Spectrum Mapper is <strong>not affiliated with, endorsed by, sponsored by, or
            associated with</strong> any of the artists, bands, record labels, or management
            companies whose works are discussed here. The names of artists and bands are used
            solely for the purpose of identification in critical and analytical commentary.
          </p>
          <p>
            All artist and band names, album titles, and song titles are the property of their
            respective owners and are used here under nominative fair use for the purpose of
            commentary, criticism, and fan discussion.
          </p>
        </Section>

        <Section title="3. Lyrics — Copyright and Attribution">
          <p>
            <strong>All song lyrics remain the exclusive intellectual property of their respective
            authors, composers, publishers, and rights holders.</strong> This site does not claim
            ownership of any lyrical content.
          </p>
          <p>
            Lyrics stored in this application are entered by the site administrator from legally
            obtained sources, used solely for the purpose of private critical analysis and fan
            commentary. They are not reproduced for commercial purposes, not distributed publicly
            in bulk, and are intended to fall within the scope of fair use (US) and fair dealing
            (UK/Commonwealth) as transformative commentary and criticism.
          </p>
          <p>
            Some lyrics may have been recalled by an AI language model (OpenAI GPT-4o Mini) from
            knowledge present in its training data. These entries are clearly labelled within the
            application as <strong>"AI recall — accuracy unverified"</strong> and are stored
            solely for private analysis purposes. AI-recalled lyrics may contain inaccuracies,
            omissions, or paraphrasing; they are not presented as authoritative transcriptions and
            are expected to be reviewed and corrected by the site administrator before being relied
            upon. The site does not use automated scraping of third-party lyric databases.
          </p>
          <p>
            If you are a rights holder and believe that content on this site infringes your copyright,
            please contact the site administrator directly. Infringing content will be removed promptly
            upon verified request.
          </p>
        </Section>

        <Section title="4. AI-Generated Analysis — Disclaimer">
          <p>
            The analysis generated by artificial intelligence on this site — including lyrical
            interpretation, music style descriptions, historical context, and spectrum scoring —
            is <strong>fan-generated critical opinion and commentary</strong>. It is produced by a
            general-purpose language model (OpenAI GPT-4o Mini) and may contain factual
            inaccuracies, subjective interpretations, or speculative statements.
          </p>
          <p>
            This site also provides an <strong>AI lyric recall</strong> feature, available to
            administrators, which asks the language model to reproduce lyrics it may have encountered
            during training. Results are stored with a source type of <em>ai_recall</em> and a
            prominent accuracy warning. The model will decline to respond if it is not confident in
            its recall. Recalled lyrics are not guaranteed to be complete or verbatim and must be
            treated as an unverified starting point only. Administrators are expected to verify and
            correct recalled lyrics before treating them as authoritative.
          </p>
          <p>
            AI analysis does not represent the views of the artists, their representatives, or any
            official source. It should be treated as one fan's interpretation — rigorous, but fallible.
            The site owner makes no representations as to the accuracy, completeness, or fitness for
            any purpose of AI-generated content.
          </p>
          <p>
            Wikipedia-sourced research content is attributed to its source. All Wikipedia content is
            licensed under the Creative Commons Attribution-ShareAlike 4.0 International License
            (CC BY-SA 4.0). Wikipedia content on this site is used in accordance with that licence.
          </p>
        </Section>

        <Section title="5. User-Generated Content">
          <p>
            Comments and ratings submitted by users are the sole responsibility of those users.
            The site owner does not endorse, verify, or take responsibility for user-submitted content.
            Users must not post content that is defamatory, harassing, or infringing on third-party rights.
          </p>
          <p>
            The site owner reserves the right to remove any user-generated content at any time, for
            any reason, without notice or explanation.
          </p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p>
            This site is provided <strong>"as is"</strong> without warranties of any kind, expressed or
            implied. The site owner shall not be liable for any direct, indirect, incidental, special,
            consequential, or punitive damages arising from your use of, or inability to use, this site
            or its content — including but not limited to damages for lost data, lost profits, or
            business interruption.
          </p>
          <p>
            The site owner makes no guarantee of uptime, data persistence, or continuity of service.
            The site may be modified, suspended, or shut down at any time without notice.
          </p>
          <p>
            Use of this site is entirely at your own risk. You are solely responsible for ensuring
            that your use of this site complies with the laws of your jurisdiction.
          </p>
        </Section>

        <Section title="7. Fair Use and Critical Commentary">
          <p>
            The use of copyrighted material on this site — including song titles, band names, and
            limited lyrical excerpts used for analysis — is believed to fall within the doctrine of
            fair use under 17 U.S.C. § 107 (United States) and equivalent provisions in other
            jurisdictions. Factors supporting fair use include:
          </p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>The purpose is non-commercial, educational, and critical/commentary in nature</li>
            <li>The use is transformative — adding analysis, interpretation, and critical value</li>
            <li>Only the minimum necessary content is used to support the commentary</li>
            <li>The use does not substitute for or harm the market for the original works</li>
          </ul>
          <p>
            Nothing on this site is intended to infringe upon the rights of any copyright holder.
            If any content is found to be in violation, it will be removed upon notification.
          </p>
        </Section>

        <Section title="8. Privacy">
          <p>
            Authentication is handled via Google OAuth 2.0. The only personal information stored is
            your Google account name, email address, and profile picture URL — used solely to
            identify your account within the application.
          </p>
          <p>
            Ratings and comments you submit are stored and may be visible to other users of the site.
            No personal information is shared with third parties. No advertising data is collected.
          </p>
        </Section>

        <Section title="9. Changes to This Notice">
          <p>
            This legal notice may be updated at any time. Continued use of the site following any
            changes constitutes acceptance of the revised terms.
          </p>
        </Section>

        <div className="border-t border-surface-200 pt-8 mt-8 text-xs text-surface-500 leading-relaxed">
          <p>
            Band Spectrum Mapper is an independent fan project. All artist names, band names, album
            titles, and song titles mentioned on this site are trademarks or registered trademarks of
            their respective owners. Their use here is for identification and commentary purposes only.
            All rights remain with the original rights holders.
          </p>
        </div>

        <div className="flex gap-4 mt-8 text-sm">
          <Link to="/" className="text-indigo-600 hover:underline">← Home</Link>
          <Link to="/help" className="text-indigo-600 hover:underline">Help & FAQ →</Link>
        </div>
      </div>
    </div>
  );
}
