// Maps SongAxisScore.source -> the shared KnowledgeConfidenceBadge vocabulary.
// Kept separate from liveFrequency.ts since it's a distinct derived concept
// (data provenance, not a display tier), following the same "one shared
// util, no page reimplements the mapping" pattern established there.

import type { ConfidenceLevel } from '../components/wiki/KnowledgeConfidenceBadge';

export type SpectrumSource = 'ai' | 'manual' | 'import' | 'audio' | null;

export function deriveSpectrumConfidence(source: SpectrumSource): {
  level: ConfidenceLevel;
  label: string;
} {
  switch (source) {
    case 'manual':
      return { level: 'verified', label: 'Hand-entered by a curator' };
    case 'audio':
      return { level: 'calculated', label: 'Derived from audio signal analysis' };
    case 'import':
      return { level: 'estimated', label: 'Loaded from an imported dataset' };
    case 'ai':
      return { level: 'ai', label: 'Generated by AI analysis of the lyrics and context' };
    default:
      // Legacy rows written before provenance tracking existed. The AI batch
      // runner is documented as BSM's primary scoring pathway, so this is the
      // most honest default — but we say so explicitly rather than claiming
      // certainty we don't have.
      return { level: 'ai', label: 'Source predates provenance tracking — likely AI-generated' };
  }
}
